package najah.edu.app;
import java.util.List;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class WebEmailService {
	
			public void sendEmail(String email,List<Home> homes){
			
				      // Put recipient’s address
				      String to = email;

				      // Put sender’s address
				      String from = "waedkhalifa5@gmail.com";
				      final String username = "waedkhalifa5@gmail.com";//username generated by Mailtrap
				      final String word = "thispass1122";//password generated by Mailtrap

				      // Paste host address from the SMTP settings tab in your Mailtrap Inbox
				      String host = "smtp.googlemail.com";

				      Properties props = new Properties();
				      props.put("mail.smtp.auth", "true");
				      props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap  
				      props.put("mail.smtp.host", host);
				      props.put("mail.smtp.port", "587");// use one of the options in the SMTP settings tab in your Mailtrap Inbox

				      // Get the Session object.
				      Session session = Session.getInstance(props,
				         new javax.mail.Authenticator() {
				    	  @Override
				            protected PasswordAuthentication getPasswordAuthentication() {
				               return new PasswordAuthentication(username, word);
				    }
				         });

				      try {
				    // Create a default MimeMessage object.
				    Message message = new MimeMessage(session);
				 
				    // Set From: header field 
				    message.setFrom(new InternetAddress(from));
				 
				    // Set To: header field
				    message.setRecipients(Message.RecipientType.TO,
				               InternetAddress.parse(to));
				 
				    // Set Subject: header field
				    message.setSubject("Here is List of Homes");
				 
				    // Put the content of your message
				    StringBuilder b = new StringBuilder();
				    for(Home home : homes) {
				    b.append(home).append("\n\n"); } 

				    String allHomes = b.toString();
				    message.setText(allHomes);

				    // Send message
				    Transport.send(message);

				      } catch (MessagingException e) {
				         throw new IllegalArgumentException(e);
				      }
				   }
}